name: Run macro-micro dummy case
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:  
  run_macro_micro_dummy:
    name: Run macro-micro dummy
    runs-on: ubuntu-latest
    container: precice/precice
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2      
      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install software-properties-common python3-dev python3-pip git apt-utils
          git clone -b release/7 https://github.com/evalf/nutils.git
          cd nutils/
          pip3 install --user .
      - name: Run macro-micro dummy
        run: |
          cp micro-manager.py macro-micro-dummy/ 
          cd macro-micro-dummy/
          python3 macro-dummy.py & python3 micro-manager.py micro-manager-dummy-config.json       
